encoder_dims:
  CONCH: 512
  H_OPTIMUS_0: 1536
  H_OPTIMUS_1: 1536
  UNI: 1024
  UNI_2: 1536
  VIRCHOW2: 1280
  KAIKO: 1024
  PHIKON: 768
  PHIKON_V2: 1024
  MIDNIGHT12K: 1536
  PRISM: 1280
  RESNET50: 2048
  HIBOU_B: 768
  HIBOU_L: 1024
  PROV_GIGAPATH_224_SLIDE: 768
  PROV_GIGAPATH_256_SLIDE: 768
  PROV_GIGAPATH_224_TILE: 1536
  PROV_GIGAPATH_256_TILE: 1536
