# Base configuration for the OAKS Toxicology Pipeline

experiment_root: "outputs/experiments/${features.encoder}/${probe.type}/k${fewshot.k}"

data:
  project_root: "/data/temporary/mika/repos/oaks_project"
  data_root: "/data/temporary/mika/repos/oaks_project/splitting_data"

  organ: "Liver"
  metadata_csv: "/data/pa_cpgarchive/archives/toxicology/open-tg-gates/metadata_SD/open_tggates_master_list.csv"

datasets:
  use_subset: false
  subset_csv: null
  subset_type: train

  train: "${data.data_root}/Splits/train.csv"
  val:   "${data.data_root}/Splits/val.csv"
  test:  "${data.data_root}/Splits/test.csv"

  # few-shot gets merged in overrides

features:
  encoder: "UNI"    
  features_root: "/data/toxicology/TG-GATES/liver
  train_animal_dir: "${features.features_root}/Training_FM/${features.encoder}/animal_features"
  val_animal_dir:   "${features.features_root}/Validation_FM/${features.encoder}/animal_features"
  in_dim: null 

aggregation:
  type: "mean"

probe:
  type: "linear"
  hidden_dim: null
  layers: null

fewshot:
  k: null

runtime:
  num_workers: 4
  batch_size: 16
  epochs: 5
  lr: 0.001

override: []
